### ISSUE TITLE
moust/psyon plugin and SplashScreen problem

### ISSUE THREAD

**Issue by adys123** [moust/phonegap-xapkreader#12]
Hi guys.
I have a problem with this plugin and the app splash screen.
The splash screen won't work anymore when I install this. When the app starts, it will display the homepage instantly.
To make the splash screen to work again, I have to install the splashscreen plugin from phonegap (`cordova plugin add org.apache.cordova.splashscreen`), then I have to add some code lines in index.html and in confing.xml. But after that, when app starts it won't display the splash screen from beginning..I mean, the app starts, a blank screen is displayed for 0.5 - 1 second then the splash appears. Sometimes instead of that blank screen i can see the homepage which is initializing.
I want to ask you guys if you know what's the conflict is?
If you need more info ask please.
Thank you.

**Comment by johnjohngc** [comment]
hello,
I have the same problem , could you explain how you have solved .
thank you in advance
